$(document).ready(function() {
	/* BASIC ;*/
	var responsiveHelper_dt_basic = undefined;
	var responsiveHelper_datatable_fixed_column = undefined;
	var responsiveHelper_datatable_col_reorder = undefined;
	var responsiveHelper_datatable_tabletools = undefined;

	var breakpointDefinition = {
		width1920:1920,
		width1024:1024,
		width480:480
	};

	$('.dt_basic').dataTable({
		"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
			"t" +
			"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
		"autoWidth": true,
		"oLanguage": {
			"sSearch": '<span class="input-group-addon"><i class="fa fa-search"></i></span>',
			"oPaginate": {
				"sPrevious": "<",
				"sNext": ">"
			}
		},
		"oTableTools": {
		        	 "aButtons": [
		             "xls",
		                {
		                    "sExtends": "pdf",
		                    "sTitle": "SmartAdmin_PDF",
		                    "sPdfMessage": "SmartAdmin PDF Export",
		                    "sPdfSize": "letter"
		                },
		             	{
	                    	"sExtends": "print",
	                    	"sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
	                	}
		             ],
		            "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
		        },
		"preDrawCallback": function() {
			// Initialize the responsive datatables helper once.
			if(!responsiveHelper_dt_basic) {
				responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('.dt_basic'), breakpointDefinition);
			}
		},
		"rowCallback": function(nRow) {
			responsiveHelper_dt_basic.createExpandIcon(nRow);
		},
		"drawCallback": function(oSettings) {
			responsiveHelper_dt_basic.respond();
		},
		"pageLength": 10,
//		"pagingType": "simple",
//		"searching": false,
		"lengthChange": false
	});
	/* END BASIC */
//	$("div.dt-toolbar").hide();
//	$("div.dt-toolbar + table").css("cssText","margin-top:0!important;");
})